### ISSUE TITLE
Aplicar transiciones a tarjeta de producto

### ISSUE THREAD

**Issue by gabrieldominguezdh10** [Kalusa93/PI#26]
- Al hacer hover sobre cualquier parte de la tarjeta deben haber transiciones para mostrar mas info del producto y el icono del camion debe girar. Esto se aplica en todos los anchos de dispositivos.

![image](https://github.com/Kalusa93/PI/assets/147005581/8e7f1d3c-2f63-450b-9831-84a033361ac4)

**Comment by Kalusa93** [comment]
Solucionado!
